name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [3.1, 3.0]
        rails: [7.0.4]
        bundler: [default]
        include:
          - { ruby: "3.1", rails: "7.0", bundler: "1" }

    name: Ruby ${{ matrix.ruby }} and Rails ${{ matrix.rails }}
    env:
      RAILS_VERSION: ${{ matrix.rails }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: ${{ matrix.bundler }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake
